### ISSUE TITLE
Unsupported Syntax Exception for line 103

### ISSUE THREAD

**Issue by Ch1hare** [2394425147/astrodx#101]
Describe the bug
When initiating the song for normal play, an error just occurred as the Screenshot shows.
And the path to open error log was nowhere to be found.

To Reproduce
1.
[2024.5.3 Fighting My Way.zip](https://github.com/2394425147/astrodx/files/15365628/2024.5.3.Fighting.My.Way.zip)
Download this file and apply common methods to unzip it under the "levels" folder (or simply unzip it correctly)
2. An error may thus be reported.

Expected behavior
The chart (fumen) should be processed properly and could be played since I have double checked the maidata grammar around line 103.

Screenshots
![Z6`@{TQ4OWONS5N47KDPVBD](https://github.com/2394425147/astrodx/assets/137185991/0dc54fb6-fc05-4c31-a039-c43c9ca9cb28)

Device specs
 - Device: iPad Pro (12.9-inch) (4th generation)
 - OS: iPadOS 17.4.1
 - Version 2.0.0 (105)

Additional context
\

**Comment by DavidScann** [comment]
This should just be a maidata error. The current version of the game (or the one that you are running it on) does not report the line with the error correctly; you may need to look around it to see which line it is that contains the error. This error has been fixed in the latest version of the game, which is not yet deployed on iOS.
