### ISSUE TITLE
iPad pro 2024:Frame Rate can not keep 120fps all the time

### ISSUE THREAD

**Issue by AhZhuzhu** [2394425147/astrodx#105]
**Describe the bug**
帧数不能一直保持120帧，在切换难度界面，开始一首歌曲，或退出游戏到后台在进入，或只在游玩过程中均会出现。
The frame rate can not keep 120fps, when it drops, the fps usually keeps 70~80fps by checking the Graphy.

**To Reproduce**
Steps to reproduce the behavior, this problem can occur during several cases:
1.Start a new song.
2.Changing the difficulty on the song selecting page.
3.Exit the game to background and then return to the game.
4.During the gameplay.

**Expected behavior**
The frame rate should be 120fps all the time.
I think this problem may be caused by the graphical driver, astroDX is not compatible with the new device.
**Screenshots**
This can be Triggered by a lot of cases.

**Device specs**
 - Device: [iPad Pro M4 256G]
 - OS: [iPados 17.5.1]
 - Version [105]

**Additional context**

**Comment by AhZhuzhu** [comment]
After testing several days,I find that  M4 iPad pro has the same strategy of promotion like iPhone（due to the same OLED screen).
So this problem may due to the new fresh ratr strategy.
Reference：https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro

**Comment by Soneoylys** [comment]
Apple forcing VSYNC with 60/80/120 etc, so even we rendered 119 FPS will locked to 80 as a result

In actual gameplay, it doesn't struggle with FPS at all
While switching pages, current scene gets unload and another one loads up, that takes some CPU times and will result have nothing to render, thus the FPS will be 0

Also because of the loading time is so fast, within one or two sample rate by Graphy, it appears to be "dropping to 80fps" while switching scenes

So there's really nothing we can do and not our fault if the FPS keeps at 120 FPS in actual gameplay, there's no game can reach 120 FPS all the time even when they loading... it just not how things works

**Comment by Soneoylys** [comment]
If you really think that's the new promotion algorithm apple stupid enough release a new device and not backwards compatible with all promotion softwares before, you can attach a gameplay video and I'll try to recompile the game with latest SDK to resolve it.
